---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# multi100

<!-- badges: start -->
<!-- badges: end -->

The goal of multi100 is to store the data preprocessing and analysis codes for the Multi 100 study.

## Folder structure

The `data/` folder contains all the datafiles that are needed to
reproduce the results of the project. The datafiles that contains
personal information are not shared (e.g. source files with email
addresses).

The `analysis/` folder contains all the analyses files in quarto documents. Within this
folder you can find the following files:

* `multi100_source_raw.qmd` file contains the
    code necessary for the transformation of the source data (the
    datafile downloaded directly from Google Forms as is) to the raw
    datafile (datafile with standard names). We also made
    sure that the raw datafiles do not contain any the email adresses of
    analysts and peer evaluators.
* `multi100_raw_processed.Rmd` file contains the
    code that cleans the dataset and transforms is into a tidy format
    ready for the analysis. We also merge the analyst responses for task 1 and task 2
    into one datafile and store the peer evaluations in a separate file.
* `multi100_analysis.Rmd` file contains the code
    for the figure creation and the analysis.

The `figures/` folder contains all the figures that are created in the
`multi100_analysis.Rmd` file.

